### ISSUE TITLE
Missing operator ON

### ISSUE THREAD

**Issue by icovada** [aurasphere/gomorra-sql#5]
There is no operator ON to express how to PESC E PESC. I propose the keyword QUANN.

Here is an example query to retrieve all post IDs created by user 'giggino'

`ripigliammo post.id mmiez' a posts pesc e pesc users quann posts.fkuser = user.pkid arò user.username = "giggino"`

**Comment by aurasphere** [comment]
Hey @icovada ! 

You are right there's no ON operator. The reason is that most of the time, you can just add the `pesc e pesc` condition into the `arò`  clause. 

So, although I find the `quann` operator a very good match for GomorraSQL, the implementation cost it's just not worth it compared to the added benefits.
