### ISSUE TITLE
Insert LIMIT Data Selections

### ISSUE THREAD

**Issue by iamelelu** [aurasphere/gomorra-sql#9]
Thanks for the innovative project, I would propose for the LIMIT Data Selections "è pccirill ashpiett" (cit. syntax from 'o Mulatto to Nina season 2). 

Here is an example query to retrieve the top 10 post IDs created by user 'giggino'

ripigliammo post.id mmiez' a posts pesc e pesc users quann posts.fkuser = user.pkid arò user.username = "giggino" è pccirill ashpiett 0, 10

**Comment by aurasphere** [comment]
Hi @iamelelu !

The problem with the LIMIT statement is that (as far as I know) [there's a different syntax between DB vendors](https://www.w3schools.com/sql/sql_top.asp) which would either tie GomorraSQL to a specific DB or require additional complex logic to detect the underlying DB and build a different query. 

This is out of scope at the moment since I think there are more relevant problem to solve (see other issues).

But thank you very much for the suggestion!
